### ISSUE TITLE
Make a blog based on a config file

### ISSUE THREAD

**Issue by TheAwiteb** [Aleecers/Aleecers.github.io#3]
<div align="center">
<img alt="Aleecers-icon" src="https://github.com/Aleecers/logos/raw/main/logos/transparent/aleecers-right-logo.svg" height="100"/>
</div>

# Config based

## Tasks
- [X] Page size
- [X] Title ( before page name )
- [X] Add pagination to title
- [X] Description
- [X] GitHub url
- [X] Twitter url
- [X] Telegram url
- [X] Blog name
- [X] About section name
- [X] Posts section name
- [X] Topics section name
- [X] About button content
- [X] Posts button content
- [X] Topics button content
- [X] Telegram button content
- [X] Site url
- [X] Main page name

## PR
- #6
